id: P007874
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG24797
  title: ལེགས་འགྲུབ་ཡོང་བ་ཇི་ལྟར་བྱེད། རི་མོའི་ལམ་ནས་ཧུའོ་དབྱིན་ཏུང་གི་སྐོར་གླེང་བ།
  author: ''
  volumes:
    3b7a79fe9ad54f328bda03d1585c847b:
      image_group_id: I1KG24799
      title: ''
      volume_number: 1
      total_pages: 201
ebook_metadata:
  title: ལེགས་འགྲུབ་ཡོང་བ་ཇི་ལྟར་བྱེད། རི་མོའི་ལམ་ནས་ཧུའོ་དབྱིན་ཏུང་གི་སྐོར་གླེང་བ།
  author: ''
  sku: P007874
  cover: cover.jpg
  layers:
  - pagination
